version: '2'
services:
  memo:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    container_name: memo
    image: memo

  mongo:
    image: mongo
    container_name: memo-mongo
